sudo: false
language: node_js
node_js: 8.11.3
env:
  global:
    - NODE_ENV=development
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd webapp
  - yarn
script:
  - yarn run build
cache:
  yarn: true
#  directories:
#    - node_modules
notifications:
  email: false
