export const LOADING_USERS_BEGIN = 'LOADING_USERS_BEGIN';
export const LOADING_USERS_COMPLETE = 'LOADING_USERS_COMPLETE';
export const LOADING_USERS_FAILED = 'LOADING_USERS_FAILED';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const SELECT_USERS_SUCCESS = 'SELECT_USERS_SUCCESS';
